### ISSUE TITLE
Log和get方法的问题

### ISSUE THREAD

**Issue by TITONIChen** [jingpeicomp/product-category-predict#3]
您好，我在本地运行了您的代码，想直接使用您已经训练好的模型，但是暂时遇到了2个问题，想向您请教一下：

1. 代码中使用了很多log.error()方法，我添加了`import org.apache.log4j.Logger;`用来初始化对象log，如`private static final Logger log = LogManager.getLogger(CategoryUtils.class);`，但是目前项目中log.error()方法仍然报错，不知道您使用的是哪个log？
2. 代码中使用了很多getXXXX( )方法，如getAppName()、getMasterUrl()、getDependenceJar()、getDependenceJar()等等，但是并没有定义具体内容，我这里大多报错了这类方法，这些定义可以省略吗？谢谢
另：为提高共同效率，大佬可以加我一下微信吗？cghcgh3333，有偿～

**Comment by jingpeicomp** [comment]
1. 使用的sl4j-api + logback 的日志打印方式
2. get/set方法是通过lombok生成的，报错估计是因为你的ide没有安装lombok插件的原因， 参考 https://projectlombok.org/setup/overview  安装插件即可
